// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5AhW7O-XeJi3Rd6douTy0BXxBlc2xvns',
    appId: '1:923673650363:web:9da8815a4a48e8a006f59e',
    messagingSenderId: '923673650363',
    projectId: 'college-event-app-f2e41',
    authDomain: 'college-event-app-f2e41.firebaseapp.com',
    storageBucket: 'college-event-app-f2e41.firebasestorage.app',
    measurementId: 'G-4Z8VDBW93K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Ke0H_nMfmWYd1PA12ay9JlVbnXP2dK0',
    appId: '1:923673650363:android:1cde5a07173ed4f906f59e',
    messagingSenderId: '923673650363',
    projectId: 'college-event-app-f2e41',
    storageBucket: 'college-event-app-f2e41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRUFdniFrNOS84ccYR7bY41xL1G0M7oV8',
    appId: '1:923673650363:ios:3e6278a1c401ff9406f59e',
    messagingSenderId: '923673650363',
    projectId: 'college-event-app-f2e41',
    storageBucket: 'college-event-app-f2e41.firebasestorage.app',
    iosBundleId: 'com.example.collegeEventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRUFdniFrNOS84ccYR7bY41xL1G0M7oV8',
    appId: '1:923673650363:ios:3e6278a1c401ff9406f59e',
    messagingSenderId: '923673650363',
    projectId: 'college-event-app-f2e41',
    storageBucket: 'college-event-app-f2e41.firebasestorage.app',
    iosBundleId: 'com.example.collegeEventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5AhW7O-XeJi3Rd6douTy0BXxBlc2xvns',
    appId: '1:923673650363:web:b58e5d5935f9d52706f59e',
    messagingSenderId: '923673650363',
    projectId: 'college-event-app-f2e41',
    authDomain: 'college-event-app-f2e41.firebaseapp.com',
    storageBucket: 'college-event-app-f2e41.firebasestorage.app',
    measurementId: 'G-BFM0TLK8TX',
  );
}
